development:
  adapter: postgresql
  encoding: unicode
  database: Malware.com
  pool: 2
  username: Malware.com
  password: tomaz
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>